### PR TITLE
Refactored main.py and added OTP endpoint routes 

### PR DESCRIPTION
**Pull request by hazra1991**
Refactored the main.py file .
Refer  to the readme for more clarification and project structure .

Added the OTP  endpoint for sending and verifying the otp .

Refactored remarks :--
  * Please let me know if any test cases fails , the refactored code has been tested in the local environment .
  * Production setting are not replicated in the local env.
  * kindly let me know if any changes need to be done or any structural changes are required 

OTP endpoint remarks:- 
  * Tested and working fine with the env 
 
Thanks !!
Abhishek Hazra

### CODE REVIEW

**Review by k-zehnder — COMMENTED** [review]
Wow, this is fantastic!! Nice work Abhishek!!! This looks great to me! As we discussed, maybe can convert to factory pattern to avoid cyclical imports. Might not be necessary though, I'm not sure. Just like the taskscheduler functionality you added, I really like your documentation on this refactored main.py -- its very helpful. Great approach I'm impressed.

**Review by Lina-Lex — APPROVED** [review]

**Review by Lina-Lex — APPROVED** [review]
Good job!

**Review by Lina-Lex — APPROVED** [review]

**Review by Lina-Lex — APPROVED** [review]
It's an amazing job! Thanks a lot

**Comment by hazra1991** [comment]
THANKS FOR THE SUPPORT !!

Will close this pull request and create a fresh request for Auto merge resolving the conflicts 

Thanks !!
Abhishek Hazra

**Pull request closed without merging**
